# Configuración para MS-LOANS (Épica 2: Préstamos y Devoluciones)
server:
  port: 0  # Puerto dinámico asignado por el sistema

spring:
  application:
    name: ms-loans
  datasource:
    url: jdbc:mysql://mysql-loans:3306/loans_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
