# Configuración para MS-REPORTS (Épica 6: Reportes y Consultas)
server:
  port: 0  # Puerto dinámico asignado por el sistema

spring:
  application:
    name: ms-reports

# MS-REPORTS no necesita base de datos propia
# Consulta a otros microservicios via RestTemplate

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
